In [1]:
import cv2, math, matplotlib.pyplot as plt, numpy as np

# Proximity between cell labels
Cоседство между метками ячеек

In [72]:
mas = np.array([
    [1,2,3],
    [8,0,4],
    [7,6,5]
])


indices = [[i[0],j[0]] for i,j in [np.where(mas == k) for k in [k for k in range(1,9)]]]

L_1_1 = np.array([
    [False,False,False],
    [False,2,False],
    [False,False,False]
])

L_1_2 = np.array([
    [True,False,True],
    [True,2,True],
    [True,True,True]
])

L_1_3 = np.array([
    [False,False,False],
    [False,2,False],
    [False,False,False]
])

L = np.stack((L_1_1,L_1_2,L_1_3))


# mas_ = np.zeros((3,3))
# mas_[0,0]



# [i,j = np.where(mas == k) for k in range (1,9)]
#for k in range (1,9):
    

#     for c in n:
#             for v in c:
#                 a,b = v
#                 if a == 2 and b == 2:continue
#                 if (0 <= i+a and i+a <= self.image.max_i) and (0 <= j+b and j+b <= self.image.max_j):
#                     self.neighbours = np.vstack((self.neighbours,[i+a,j+b]))
#         self.neighbours = np.delete(self.neighbours,0, axis = 0) 
    

1

In [73]:
L

array([[[0, 0, 0],
        [0, 2, 0],
        [0, 0, 0]],

       [[1, 0, 1],
        [1, 2, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 2, 0],
        [0, 0, 0]]])

In [75]:
L[2,1,1]

2

# Image and its data
Изображение и его данные

In [10]:
class Image(object):
    def __init__(self, path):
        self.img = cv2.imread(path, cv2.IMREAD_UNCHANGED)
        print('Original Dimensions : ',self.img.shape)
        self.max_i, self.max_j, _ = self.img.shape
        
    # Resize image size
    # Изменить размер изображения
    def resize (self):
        width = 300
        height = 600
        dim = (height,width)
        
        self.max_i = height
        self.max_j = width

        # resize image
        self.reimg = cv2.resize(self.img, dim, interpolation = cv2.INTER_AREA)
        print('Resized Dimensions : ', self.reimg.shape)
        

In [11]:
i = 1
path = f"./img/img{i}.jpg"
img = Image(path)

Original Dimensions :  (380, 605, 3)


# Normal distribution for part of the image
Нормальное распределение для части изображения



In [29]:
class Normal_distribution (object):   
    def __init__(self, image):
        self.data = self.M_σ(image.img)
    def M_σ(self,image):
        mas = np.array(image[0])
        for i in range(1,len(image)):
            np.vstack((mas,image[i]))
        image_n = mas
        mean = np.mean(image_n,axis=0); sigma=np.var(image_n,axis=0); cov = np.cov(mas,rowvar=False)
        print('DATA','\n','M = ',mean,'\n','σ = ',sigma,'\n', 'cov = ','\n',cov)
        return [mean,cov]

In [30]:
normal_distribution = Normal_distribution(img)

DATA 
 M =  [195.19504132 130.09090909  57.21983471] 
 σ =  [ 42.33220682  69.09090909 187.00125948] 
 cov =  
 [[ 42.40229325  53.49879591  87.29314487]
 [ 53.49879591  69.20529801 112.89720048]
 [ 87.29314487 112.89720048 187.31086421]]


# Cell and its neighbors
Ячейка и ее соседи

In [17]:
class Сell(object):
    def __init__(self,image, i, j):
        self.image = image 
        self.i = i
        self.j = j
        self.find_neighbours(i,j)
        
    # Find neighbors of a cell in an image  
    # Найти соседей яейки изображения
    def find_neighbours(self,i,j):
        self.neighbours = np.array([[0,0]])
        n = np.array([
            [(-1,-1),(0,-1),(1,-1)],
            [(-1,0),(2,2),(1,0)],
            [(-1,1),(0,1),(1,1)]
        ])
        for c in n:
            for v in c:
                a,b = v
                if a == 2 and b == 2:continue
                if (0 <= i+a and i+a <= self.image.max_i) and (0 <= j+b and j+b <= self.image.max_j):
                    self.neighbours = np.vstack((self.neighbours,[i+a,j+b]))
        self.neighbours = np.delete(self.neighbours,0, axis = 0) 
        
#     def __del__(self):
#         del self.image
#         del self.i
#         del self.j
#         del self.neighbours
        
                    
A = Сell(img,100,100)
A.neighbours  

array([[ 99,  99],
       [100,  99],
       [101,  99],
       [ 99, 100],
       [101, 100],
       [ 99, 101],
       [100, 101],
       [101, 101]])

In [20]:
cell = Сell(img,0,0)
cell.neighbours 

array([[1, 0],
       [0, 1],
       [1, 1]])

# Some tests and usefull info
Немного тестов и полезной информации


In [ ]:
# class Foo(Bar):
#     def baz(self, arg):
#         return super().baz(arg)


# class A(object):     # deriving from 'object' declares A as a 'new-style-class'
#     def foo(self):
#         print "foo"

# class B(A):
#     def foo(self):
#         super(B, self).foo()   # calls 'A.foo()'

# myB = B()
# myB.foo()

class A():
  def bar(self, string):
    print("Hi, I'm bar, inherited from A"+string)

class B(A):
  def baz(self):
    self.bar(" - called by baz in B")

B().baz() # prints out "Hi, I'm bar, inherited from A - called by baz in B"

#https://younglinux.info/oopython/objects
class B:
    n = 5
    def adder(self, v):
        return v + self.n
 
w = B()
w.__dict__
w.n = 8
w.__dict__

w.__dict__['m'] = 100
w.__dict__
w.m
w.__dict__

In [15]:
class Salary(object):
    def __init__(self, pay):
        self.pay = pay

    def getTotal(self):
        return (self.pay * 12)

class Employee(object):
    def __init__(self, pay, bonus):
        self.pay = pay
        self.bonus = bonus

    def annualSalary(self):
        return "Total: " + str(self.pay.getTotal() + self.bonus)

salary = Salary(100)
employee = Employee(salary, 10)
print(employee.annualSalary())

Total: 1210


In [2]:
mas_1 = np.array([
    [0,0,0],
    [0,1,0],
    [0,0,0]
])
mas_2 = np.array([
    [0,0,0],
    [0,1,0],
    [0,0,0]
])

In [3]:
i,j = [(0,1),(2,0)][0]

In [47]:
neighbours = np.array([
    [(-1,-1),(0,-1),(1,-1)],
    [(-1,0),(2,2),(1,0)],
    [(-1,1),(0,1),(1,1)]
])
neighbours.shape

(3, 3, 2)

In [5]:
for i in neighbours:
    for j in i:
        a,b = j
        if a == 2 and b == 2:continue
        print(a,b)

-1 -1
0 -1
1 -1
-1 0
1 0
-1 1
0 1
1 1
